### ISSUE TITLE
IZAR RC 868 i W R4 compatibility

### ISSUE THREAD

**Issue by a-d-r-i-a-n-d** [zibous/ha-watermeter#11]
![tempImage1Lep9k](https://user-images.githubusercontent.com/125617841/222932181-e127b8ea-e368-4575-89d5-39aa833400b7.gif)

Hi,
Thanks for your hard work. I live in UK and I wanted to check if this would work with the meter from the above picture. Any help is much appreciated.
Cheers.

**Comment by zibous** [comment]
Yes i think it ist working, because it ist a 868 device.

**Comment by urechi** [comment]
Thanks @zibous, I will give it a go.

**Comment by a-d-r-i-a-n-d** [comment]
Hi @zibous ,

I've managed to flash it tonight but I get some errors:
```
wMBus-lib: Error during decoding '3 out of 6'
```
Full logs file here:
[logs.txt](https://github.com/zibous/ha-watermeter/files/10937556/logs.txt)

Any help is much appreciated.

**Comment by a-d-r-i-a-n-d** [comment]
Hi @zibous ,

I've managed to flash it tonight but I get some errors:
```
wMBus-lib: Error during decoding '3 out of 6'
```
Full logs file here:
[logs.txt](https://github.com/zibous/ha-watermeter/files/10937600/logs.txt)

Any help is much appreciated.

**Comment by zibous** [comment]
@a-d-r-i-a-n-d 
Sorry but i am on Holiday and will be back next week.

**Comment by a-d-r-i-a-n-d** [comment]
No worries, enjoy your holiday. I’ll speak to you next week.

**Comment by a-d-r-i-a-n-d** [comment]
I don't see that error anymore since I worked out my hex meter id and used the correct one in `secrets.yaml`
That being said I am now trying to understand the readings.


<img width="1728" alt="Screenshot 2023-03-10 at 18 07 40" src="https://user-images.githubusercontent.com/125617841/224393323-404b9def-a555-48b2-94c5-8b4448f7ead9.png">

**Comment by zibous** [comment]
Yes also in my case only the hex Meter id ist working. You have negative values, reset the globals or edit the inital valuest in the yaml config. Alternative you can Set the valuest with a homeassistant service call.
