### ISSUE TITLE
ESP32 SX1276

### ISSUE THREAD

**Issue by PauloMPereira** [zibous/ha-watermeter#30]
Hello ,

This project is compatibly with ESP32 SX1276?
Device link: [Aliexpress](https://pt.aliexpress.com/item/1005005967763162.html?spm=a2g0o.order_list.order_list_main.5.248ccaa4dAZqB9&gatewayAdapt=glo2bra)

Also is it possible to confirm that my water meter is compatible?
Water Meter Images:
![watermeter1](https://github.com/zibous/ha-watermeter/assets/1873373/f0b555b5-ddb9-46bb-8bdd-03ab325ab9dd)
![watermeter2](https://github.com/zibous/ha-watermeter/assets/1873373/c8b1796f-0e3f-4392-8ae9-562ae643d563)

Best regards,
Paulo

**Comment by SzczepanLeon** [comment]
> This project is compatibly with ESP32 SX1276?

No, only CC1101 is supported.

> Also is it possible to confirm that my water meter is compatible?

Should be. Please include photo from other side.

**Comment by PauloMPereira** [comment]
Ok I saw the reference and it looks like that it's the same:
![watermeter3](https://github.com/zibous/ha-watermeter/assets/1873373/5f4b3bc5-2fb9-49b3-a02b-99bedc03cdf1)

**Comment by zibous** [comment]
> This project is compatibly with ESP32 SX1276?
> Device link: [Aliexpress](https://pt.aliexpress.com/item/1005005967763162.html?spm=a2g0o.order_list.order_list_main.5.248ccaa4dAZqB9&gatewayAdapt=glo2bra)

Hi,
Negativ, you can't use ESP32 SX1276. Only ESP32 +  CC1101 is supported.
