### ISSUE TITLE
Question IPERL SENSUS

### ISSUE THREAD

**Issue by nibi79** [zibous/ha-watermeter#48]
hi,

I have received a new water meter "IPERL SENSUS" and also got the API key for it. 
Is the IPERL supported at all? And where must the API key be entered?

tx

**Comment by zibous** [comment]
Hi

Possibly, IPERL should work, but I don't know if IPERL SENSUS works. 

> Is the IPERL supported at all? And where must the API key be entered?

```
  - platform: wmbus
    meter_id:  ID FROM LOG
    type: iperl
    key: "-- YOUR KEY--"
```	
-  meter_id (Optional, int): Meter ID. Can be specified as decimal or hex. Defaults to 0.
- type (Optional, string): Meter type. Currently amiplus, apator08, apator162, apatoreitn, bmeters, c5isf, compact5, dme07, elf, evo868, fhkvdataiii, flowiq2200, hydrocalm3, hydrodigit, hydrus, iperl, itron, izar, kamheat, mkradio3, mkradio4, mkradio4a, multical21, qheat, qwater, sharky774, topaseskr, ultrimis, unismart, vario451 are supported. Defaults to unknown.
- key (Optional): Key for meter, used in payload decoding process. Defaults to "".


You can find more information here:

see: https://github.com/SzczepanLeon/esphome-components
