### ISSUE TITLE
No longer working after update of esphome-components

### ISSUE THREAD

**Issue by evilmumi** [zibous/ha-watermeter#49]
Do you have a working version - after update of Leon:

`INFO ESPHome 2024.9.1
INFO Reading configuration /config/esphome/testtestesp32.yaml...
INFO Updating https://github.com/SzczepanLeon/esphome-components.git@main
INFO Updating https://github.com/zdzichu6969/esphome-components.git@None
INFO Updating https://github.com/TheStaticTurtle/esphome_syslog.git@None
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

  [mode] is an invalid option for [sensor.wmbus]. Please check the indentation.

    [add_prefix] is an invalid option for [sensor.wmbus]. Please check the indentation.
 
    [target_water_m3] is an invalid option for [sensor.wmbus]. Please check the indentation.
  
  [status] is an invalid option for [sensor.wmbus]. Please check the indentation.

    [volume_flow_lh] is an invalid option for [sensor.wmbus]. Please check the indentation.
   
  [max_flow_lh] is an invalid option for [sensor.wmbus]. Please check the indentation.
  
  [lqi] is an invalid option for [sensor.wmbus]. Please check the indentation.

    [rssi] is an invalid option for [sensor.wmbus]. Please check the indentation.
 
  [total_water_m3] is an invalid option for [sensor.wmbus]. Please check the indentation.
    [current_month_total_water_l] is an invalid option for [sensor.wmbus]. Please check the indentation.
  
  [last_month_total_water_m3] is an invalid option for [sensor.wmbus]. Please check the indentation.
  [remaining_battery_life_y] is an invalid option for [sensor.wmbus]. Please check the indentation.
  
    [transmit_period_s] is an invalid option for [sensor.wmbus]. Please check the indentation.

    [current_alarms] is an invalid option for [sensor.wmbus]. Please check the indentation.
    
  [previous_alarms] is an invalid option for [sensor.wmbus]. Please check the indentation.
 `

**Comment by gatismu** [comment]
little offtopic, but would it be possible to read data from thermal energy meter?
https://www.bmeters.com/wp-content/uploads/2022/06/v1.1_HYDROCAL-M4-User-Manual_EN.pdf
I tried to scan with this (made one more esp32 board) but currently I did not saw it, could be it does not broadcast anything yet as heating season has not yet started. theoretically I could get telegramm and transfer that decoded number to Homeassistant and define that it is MWh.. theoretically.
Thanks!
