### ISSUE TITLE
Setup issues latest ESPHome

### ISSUE THREAD

**Issue by apedance** [zibous/ha-watermeter#51]
Hey, there.
I bought all the parts the there are issues with wmbus...
Help appreciated.

![image](https://github.com/user-attachments/assets/b9d80305-5883-4cec-8d0b-63ba049c8b59)

`INFO ESPHome 2024.9.1
INFO Reading configuration /config/esphome/esphome-web-cd69f0.yaml...
INFO Updating https://github.com/SzczepanLeon/esphome-components.git@main
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

sensor.wmbus: [source /config/esphome/esphome-web-cd69f0.yaml:317]
  platform: wmbus
  meter_id: 0
  type: izar
  
  [add_prefix] is an invalid option for [sensor.wmbus]. Please check the indentation.
  add_prefix: True
  
  [lqi] is an invalid option for [sensor.wmbus]. Please check the indentation.
  lqi: 
    id: wmbus_cc1101_lqi
    name: Watermeter CC1101 LQI
    unit_of_measurement: lqi
    entity_category: diagnostic
  
  [rssi] is an invalid option for [sensor.wmbus]. Please check the indentation.
  rssi: 
    id: wmbus_cc1101_rssi
    name: Watermeter CC1101 RSSI
    unit_of_measurement: %
    entity_category: diagnostic
  
  [total_water_m3] is an invalid option for [sensor.wmbus]. Please check the indentation.
  total_water_m3: 
    id: waterdisplay
    name: Watermeter Display
    unit_of_measurement: m³
    state_class: total_increasing
    device_class: water
    accuracy_decimals: 3
    icon: mdi:counter
    on_value: 
      then: 
        - lambda: |-
            ESP_LOGI("wmbus", "Water Display value: %.3f, last value: %.3f", id(waterdisplay).state, id(last_value));
            id(last_value)=id(waterdisplay).state;
  
  [last_month_total_water_m3] is an invalid option for [sensor.wmbus]. Please check the indentation.
  last_month_total_water_m3: 
    name: Water last month
    id: waterdisplay_lastmonth
    unit_of_measurement: m³
    state_class: total_increasing
    device_class: water
    accuracy_decimals: 3
    icon: mdi:counter
  
  [current_month_total_water_l] is an invalid option for [sensor.wmbus]. Please check the indentation.
  current_month_total_water_l: 
    name: Water current month
    id: watermonth
    accuracy_decimals: 2
    unit_of_measurement: L
    state_class: total_increasing
    device_class: water
  
  [remaining_battery_life_y] is an invalid option for [sensor.wmbus]. Please check the indentation.
  remaining_battery_life_y: 
    name: Watermeter Battery Life
    id: watermeter_batterie
    accuracy_decimals: 2
    unit_of_measurement: Years
    icon: mdi:battery
  
  [transmit_period_s] is an invalid option for [sensor.wmbus]. Please check the indentation.
  transmit_period_s: 
    name: Watermeter transmit periode
    id: watermeter_transmit_periode
    unit_of_measurement: sec
    accuracy_decimals: 2
    icon: mdi:timelapse
  
  [current_alarms] is an invalid option for [sensor.wmbus]. Please check the indentation.
  current_alarms: 
    id: watermeter_current_alarms
    name: Watermeter current alarm code
    icon: mdi:alarm-light
    entity_category: diagnostic
  
  [previous_alarms] is an invalid option for [sensor.wmbus]. Please check the indentation.
  previous_alarms: 
    id: watermeter_previous_alarms
    name: Watermeter pervious alarm code
`

Thanks.

**Comment by SzczepanLeon** [comment]
Please find in YAML line external_components, and modyfi it to:
```
  - source: github://SzczepanLeon/esphome-components@3.2.3
```
